config/routes.rb
Rails.application.routes.draw do

  get 'cart' => 'carts#show'

  resources :cart_items, only: [:create]

  root 'top#index'

end

app/models/cart.rb
# == Schema Information
#
# Table name: carts
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Cart < ActiveRecord::Base
  has_many :cart_items
  has_many :products, through: :cart_items
end

app/models/cart_item.rb
# == Schema Information
#
# Table name: cart_items
#
#  id         :integer          not null, primary key
#  cart_id    :integer
#  product_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_cart_items_on_cart_id     (cart_id)
#  index_cart_items_on_product_id  (product_id)
#

class CartItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :product
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string
#  price       :integer
#  description :text
#  image       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Product < ActiveRecord::Base
  validates :name,presence: true,
                  length: { in: 3..140 }
  validates :price,presence: true,
                   numericality: { only_integer: true,
                                   greater_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_cart

  private

    def set_cart
      @cart = Cart.includes(:products).find_or_create_by(id: session[:cart_id])
      session[:cart_id] = @cart.id
    end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def create

   @cart.cart_items.create(cart_item_params)
   redirect_to root_url, notice: 'カートに商品を追加'
  end

  private

  def cart_item_params
    params.permit(:product_id)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @products = Product.all.page params[:page]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/cart_items/create.html.erb
<h1>CartItems#create</h1>
<p>Find me in app/views/cart_items/create.html.erb</p>

app/views/carts/show.html.erb
<h1>カート</h1>

<table class="table table-striped">
 <thead>
  <tr>
    <th>No</th>
    <th>商品名</th>
    <th>価格</th>
    <th></th>
  </tr>
</thead>
<tbody>
  <% @cart.cart_items.each_with_index do |item, i| %>
  <tr>
    <td><%= i+1 %></td>
    <td><%= item.product.name %></td>
    <td><%= number_to_currency(item.product.price) %></td>
    <td>削除</td>
  </tr>
  <% end %>
</tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DepotVer2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Brand</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
          <li><a href="#">Link</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        </ul>
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#">Link</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/top/index.html.erb
<h1>ようこそ</h1>

<div id="cart">
<p>カートNo:<%= @cart.id %></p>
<p>カートの中身は<%= @cart.cart_items.count %>個の商品があります。</p>
<p><%= link_to('カートを表示する',cart_path) %></p>
</div>


<ul class="media-list">
<% @products.each do |product| %>
  <li class="media">
    <div class="media-left">
      <a href="#">
        <img class="media-object" src="<%= product.image %>" alt="...">
      </a>
    </div>
    <div class="media-body">
      <h4 class="media-heading"><%= product.name %></h4>
      <p><%= product.description %></p>
      <p><%= number_to_currency(product.price) %></p>
      <%= button_to('カートに追加', cart_items_path(product_id: product),class: 'btn btn-primary') %>
    </div>
  </li>
  <%end%>
</ul>

<%= paginate @products %>